---
- name: set bios and board variable for checks
  ansible.builtin.set_fact:
    ansible_bios_board_check: "{{ ' '.join(to_join_list) }}"
  vars:
    to_join_list:
      - "{{ ansible_bios_version | default('') }}"
      - "{{ ansible_bios_vendor | default('') }}"
      - "{{ ansible_board_vendor | default('') }}"
      - "{{ ansible_chassis_asset_tag | default('') }}"
      - "{{ ansible_chassis_vendor | default('') }}"

- name: check for AWS BIOS vendor
  ansible.builtin.set_fact:
    auto_registration_provider: AWS
  when:
    - auto_registration_provider is not defined or auto_registration_provider | trim | length == 0
    - ansible_bios_board_check is search('(?i)amazon')

- name: check for Azure asset tag
  block:
    - name: find asset tag via dmi (Ansible <2.10)
      ansible.builtin.slurp:
        src: /sys/devices/virtual/dmi/id/chassis_asset_tag
      register: chassis_asset_tag_file
      when: ansible_chassis_asset_tag is not defined

    - name: set ansible_chassis_asset_tag fact for future compatibility
      ansible.builtin.set_fact:
        ansible_chassis_asset_tag: "{{ chassis_asset_tag_file['content'] | b64decode | trim }}"
      when: chassis_asset_tag_file is not skipped

    - name: check for Azure asset tag
      ansible.builtin.set_fact:
        auto_registration_provider: MSAZ
      when: ansible_chassis_asset_tag is defined and ansible_chassis_asset_tag == '7783-7084-3265-9085-8269-3286-77'
  when: auto_registration_provider is not defined

- name: check for GCP system product
  block:
    - name: get system product name
      command: dmidecode -s system-product-name
      become: true
      register: system_product_name_out
      changed_when: false

    - name: check for GCE system product then set auto registration provider to GCE
      ansible.builtin.set_fact:
        auto_registration_provider: GCE
      when: system_product_name_out.stdout == "Google Compute Engine"
  when: auto_registration_provider is not defined

- name: ensure cloud provider was detected or already provided
  fail:
    msg: Unable to detect cloud provider for host
  when: auto_registration_provider is not defined
