---
- include_tasks: detect_provider.yml

- include_tasks: aws.yml
  when: auto_registration_provider == 'AWS'

- include_tasks: azure.yml
  when: auto_registration_provider == 'MSAZ'

- include_tasks: gcp.yml
  when: auto_registration_provider == 'GCE'

- include_tasks: verify.yml
