---
- include: detect_provider.yml

- include: aws.yml
  when: auto_registration_provider == 'AWS'

- include: azure.yml
  when: auto_registration_provider == 'MSAZ'

- include: gcp.yml
  when: auto_registration_provider == 'GCE'

- include: verify.yml
