---
galaxy_info:
  author: Red Hat, Inc.
  description: Verify a cloud provider account for use with RHSM auto registration
  company: Red Hat, Inc.
  license: Apache License 2.0
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
        - 8
  categories:
    - cloud
    - system
  dependencies: []